//C++ Abstract Syntax Implementation generated by the BNF Converter.
#include <algorithm>
#include <string>
#include <iostream>
#include <vector>
#include "Absyn.H"
namespace pcfg
{
/********************   Gram    ********************/
Gram::Gram(ListRule *p1)
{
  listrule_ = p1;

}

Gram::Gram(const Gram & other)
{
  listrule_ = other.listrule_->clone();

}

Gram &Gram::operator=(const Gram & other)
{
  Gram tmp(other);
  swap(tmp);
  return *this;
}

void Gram::swap(Gram & other)
{
  std::swap(listrule_, other.listrule_);

}

Gram::~Gram()
{
  delete(listrule_);

}

void Gram::accept(Visitor *v)
{
  v->visitGram(this);
}

Gram *Gram::clone() const
{
  return new Gram(*this);
}



/********************   Rul    ********************/
Rul::Rul(Prob *p1, LHS *p2, ListRHS *p3)
{
  prob_ = p1;
  lhs_ = p2;
  listrhs_ = p3;

}

Rul::Rul(const Rul & other)
{
  prob_ = other.prob_->clone();
  lhs_ = other.lhs_->clone();
  listrhs_ = other.listrhs_->clone();

}

Rul &Rul::operator=(const Rul & other)
{
  Rul tmp(other);
  swap(tmp);
  return *this;
}

void Rul::swap(Rul & other)
{
  std::swap(prob_, other.prob_);
  std::swap(lhs_, other.lhs_);
  std::swap(listrhs_, other.listrhs_);

}

Rul::~Rul()
{
  delete(prob_);
  delete(lhs_);
  delete(listrhs_);

}

void Rul::accept(Visitor *v)
{
  v->visitRul(this);
}

Rul *Rul::clone() const
{
  return new Rul(*this);
}



/********************   ERul    ********************/
ERul::ERul()
{

}

ERul::ERul(const ERul & other)
{

}

ERul &ERul::operator=(const ERul & other)
{
  ERul tmp(other);
  swap(tmp);
  return *this;
}

void ERul::swap(ERul & other)
{

}

ERul::~ERul()
{

}

void ERul::accept(Visitor *v)
{
  v->visitERul(this);
}

ERul *ERul::clone() const
{
  return new ERul(*this);
}



/********************   LhsS    ********************/
LhsS::LhsS(Ident p1)
{
  ident_ = p1;

}

LhsS::LhsS(const LhsS & other)
{
  ident_ = other.ident_;

}

LhsS &LhsS::operator=(const LhsS & other)
{
  LhsS tmp(other);
  swap(tmp);
  return *this;
}

void LhsS::swap(LhsS & other)
{
  std::swap(ident_, other.ident_);

}

LhsS::~LhsS()
{

}

void LhsS::accept(Visitor *v)
{
  v->visitLhsS(this);
}

LhsS *LhsS::clone() const
{
  return new LhsS(*this);
}



/********************   ProbR    ********************/
ProbR::ProbR(Double p1)
{
  double_ = p1;

}

ProbR::ProbR(const ProbR & other)
{
  double_ = other.double_;

}

ProbR &ProbR::operator=(const ProbR & other)
{
  ProbR tmp(other);
  swap(tmp);
  return *this;
}

void ProbR::swap(ProbR & other)
{
  std::swap(double_, other.double_);

}

ProbR::~ProbR()
{

}

void ProbR::accept(Visitor *v)
{
  v->visitProbR(this);
}

ProbR *ProbR::clone() const
{
  return new ProbR(*this);
}



/********************   ProbA    ********************/
ProbA::ProbA(Integer p1)
{
  integer_ = p1;

}

ProbA::ProbA(const ProbA & other)
{
  integer_ = other.integer_;

}

ProbA &ProbA::operator=(const ProbA & other)
{
  ProbA tmp(other);
  swap(tmp);
  return *this;
}

void ProbA::swap(ProbA & other)
{
  std::swap(integer_, other.integer_);

}

ProbA::~ProbA()
{

}

void ProbA::accept(Visitor *v)
{
  v->visitProbA(this);
}

ProbA *ProbA::clone() const
{
  return new ProbA(*this);
}



/********************   RhsDisjSyms    ********************/
RhsDisjSyms::RhsDisjSyms(Ident p1)
{
  ident_ = p1;

}

RhsDisjSyms::RhsDisjSyms(const RhsDisjSyms & other)
{
  ident_ = other.ident_;

}

RhsDisjSyms &RhsDisjSyms::operator=(const RhsDisjSyms & other)
{
  RhsDisjSyms tmp(other);
  swap(tmp);
  return *this;
}

void RhsDisjSyms::swap(RhsDisjSyms & other)
{
  std::swap(ident_, other.ident_);

}

RhsDisjSyms::~RhsDisjSyms()
{

}

void RhsDisjSyms::accept(Visitor *v)
{
  v->visitRhsDisjSyms(this);
}

RhsDisjSyms *RhsDisjSyms::clone() const
{
  return new RhsDisjSyms(*this);
}



/********************   RhsDisjSymsP    ********************/
RhsDisjSymsP::RhsDisjSymsP(Ident p1)
{
  ident_ = p1;

}

RhsDisjSymsP::RhsDisjSymsP(const RhsDisjSymsP & other)
{
  ident_ = other.ident_;

}

RhsDisjSymsP &RhsDisjSymsP::operator=(const RhsDisjSymsP & other)
{
  RhsDisjSymsP tmp(other);
  swap(tmp);
  return *this;
}

void RhsDisjSymsP::swap(RhsDisjSymsP & other)
{
  std::swap(ident_, other.ident_);

}

RhsDisjSymsP::~RhsDisjSymsP()
{

}

void RhsDisjSymsP::accept(Visitor *v)
{
  v->visitRhsDisjSymsP(this);
}

RhsDisjSymsP *RhsDisjSymsP::clone() const
{
  return new RhsDisjSymsP(*this);
}



/********************   RhsDisjSymsA    ********************/
RhsDisjSymsA::RhsDisjSymsA(Ident p1)
{
  ident_ = p1;

}

RhsDisjSymsA::RhsDisjSymsA(const RhsDisjSymsA & other)
{
  ident_ = other.ident_;

}

RhsDisjSymsA &RhsDisjSymsA::operator=(const RhsDisjSymsA & other)
{
  RhsDisjSymsA tmp(other);
  swap(tmp);
  return *this;
}

void RhsDisjSymsA::swap(RhsDisjSymsA & other)
{
  std::swap(ident_, other.ident_);

}

RhsDisjSymsA::~RhsDisjSymsA()
{

}

void RhsDisjSymsA::accept(Visitor *v)
{
  v->visitRhsDisjSymsA(this);
}

RhsDisjSymsA *RhsDisjSymsA::clone() const
{
  return new RhsDisjSymsA(*this);
}



/********************   RhsDisjTerminal    ********************/
RhsDisjTerminal::RhsDisjTerminal(String p1)
{
  string_ = p1;

}

RhsDisjTerminal::RhsDisjTerminal(const RhsDisjTerminal & other)
{
  string_ = other.string_;

}

RhsDisjTerminal &RhsDisjTerminal::operator=(const RhsDisjTerminal & other)
{
  RhsDisjTerminal tmp(other);
  swap(tmp);
  return *this;
}

void RhsDisjTerminal::swap(RhsDisjTerminal & other)
{
  std::swap(string_, other.string_);

}

RhsDisjTerminal::~RhsDisjTerminal()
{

}

void RhsDisjTerminal::accept(Visitor *v)
{
  v->visitRhsDisjTerminal(this);
}

RhsDisjTerminal *RhsDisjTerminal::clone() const
{
  return new RhsDisjTerminal(*this);
}



/********************   RhsDisj    ********************/
RhsDisj::RhsDisj(ListDRHS *p1)
{
  listdrhs_ = p1;

}

RhsDisj::RhsDisj(const RhsDisj & other)
{
  listdrhs_ = other.listdrhs_->clone();

}

RhsDisj &RhsDisj::operator=(const RhsDisj & other)
{
  RhsDisj tmp(other);
  swap(tmp);
  return *this;
}

void RhsDisj::swap(RhsDisj & other)
{
  std::swap(listdrhs_, other.listdrhs_);

}

RhsDisj::~RhsDisj()
{
  delete(listdrhs_);

}

void RhsDisj::accept(Visitor *v)
{
  v->visitRhsDisj(this);
}

RhsDisj *RhsDisj::clone() const
{
  return new RhsDisj(*this);
}



/********************   RhsSymbol    ********************/
RhsSymbol::RhsSymbol(Ident p1)
{
  ident_ = p1;

}

RhsSymbol::RhsSymbol(const RhsSymbol & other)
{
  ident_ = other.ident_;

}

RhsSymbol &RhsSymbol::operator=(const RhsSymbol & other)
{
  RhsSymbol tmp(other);
  swap(tmp);
  return *this;
}

void RhsSymbol::swap(RhsSymbol & other)
{
  std::swap(ident_, other.ident_);

}

RhsSymbol::~RhsSymbol()
{

}

void RhsSymbol::accept(Visitor *v)
{
  v->visitRhsSymbol(this);
}

RhsSymbol *RhsSymbol::clone() const
{
  return new RhsSymbol(*this);
}



/********************   RhsSymbolP    ********************/
RhsSymbolP::RhsSymbolP(Ident p1)
{
  ident_ = p1;

}

RhsSymbolP::RhsSymbolP(const RhsSymbolP & other)
{
  ident_ = other.ident_;

}

RhsSymbolP &RhsSymbolP::operator=(const RhsSymbolP & other)
{
  RhsSymbolP tmp(other);
  swap(tmp);
  return *this;
}

void RhsSymbolP::swap(RhsSymbolP & other)
{
  std::swap(ident_, other.ident_);

}

RhsSymbolP::~RhsSymbolP()
{

}

void RhsSymbolP::accept(Visitor *v)
{
  v->visitRhsSymbolP(this);
}

RhsSymbolP *RhsSymbolP::clone() const
{
  return new RhsSymbolP(*this);
}



/********************   RhsSymbolA    ********************/
RhsSymbolA::RhsSymbolA(Ident p1)
{
  ident_ = p1;

}

RhsSymbolA::RhsSymbolA(const RhsSymbolA & other)
{
  ident_ = other.ident_;

}

RhsSymbolA &RhsSymbolA::operator=(const RhsSymbolA & other)
{
  RhsSymbolA tmp(other);
  swap(tmp);
  return *this;
}

void RhsSymbolA::swap(RhsSymbolA & other)
{
  std::swap(ident_, other.ident_);

}

RhsSymbolA::~RhsSymbolA()
{

}

void RhsSymbolA::accept(Visitor *v)
{
  v->visitRhsSymbolA(this);
}

RhsSymbolA *RhsSymbolA::clone() const
{
  return new RhsSymbolA(*this);
}



/********************   RhsTerminal    ********************/
RhsTerminal::RhsTerminal(String p1)
{
  string_ = p1;

}

RhsTerminal::RhsTerminal(const RhsTerminal & other)
{
  string_ = other.string_;

}

RhsTerminal &RhsTerminal::operator=(const RhsTerminal & other)
{
  RhsTerminal tmp(other);
  swap(tmp);
  return *this;
}

void RhsTerminal::swap(RhsTerminal & other)
{
  std::swap(string_, other.string_);

}

RhsTerminal::~RhsTerminal()
{

}

void RhsTerminal::accept(Visitor *v)
{
  v->visitRhsTerminal(this);
}

RhsTerminal *RhsTerminal::clone() const
{
  return new RhsTerminal(*this);
}



/********************   RhsEpsilon    ********************/
RhsEpsilon::RhsEpsilon()
{

}

RhsEpsilon::RhsEpsilon(const RhsEpsilon & other)
{

}

RhsEpsilon &RhsEpsilon::operator=(const RhsEpsilon & other)
{
  RhsEpsilon tmp(other);
  swap(tmp);
  return *this;
}

void RhsEpsilon::swap(RhsEpsilon & other)
{

}

RhsEpsilon::~RhsEpsilon()
{

}

void RhsEpsilon::accept(Visitor *v)
{
  v->visitRhsEpsilon(this);
}

RhsEpsilon *RhsEpsilon::clone() const
{
  return new RhsEpsilon(*this);
}



/********************   RhsBr    ********************/
RhsBr::RhsBr(ListBRHS *p1)
{
  listbrhs_ = p1;

}

RhsBr::RhsBr(const RhsBr & other)
{
  listbrhs_ = other.listbrhs_->clone();

}

RhsBr &RhsBr::operator=(const RhsBr & other)
{
  RhsBr tmp(other);
  swap(tmp);
  return *this;
}

void RhsBr::swap(RhsBr & other)
{
  std::swap(listbrhs_, other.listbrhs_);

}

RhsBr::~RhsBr()
{
  delete(listbrhs_);

}

void RhsBr::accept(Visitor *v)
{
  v->visitRhsBr(this);
}

RhsBr *RhsBr::clone() const
{
  return new RhsBr(*this);
}



/********************   RhsBrPlus    ********************/
RhsBrPlus::RhsBrPlus(ListBRHS *p1)
{
  listbrhs_ = p1;

}

RhsBrPlus::RhsBrPlus(const RhsBrPlus & other)
{
  listbrhs_ = other.listbrhs_->clone();

}

RhsBrPlus &RhsBrPlus::operator=(const RhsBrPlus & other)
{
  RhsBrPlus tmp(other);
  swap(tmp);
  return *this;
}

void RhsBrPlus::swap(RhsBrPlus & other)
{
  std::swap(listbrhs_, other.listbrhs_);

}

RhsBrPlus::~RhsBrPlus()
{
  delete(listbrhs_);

}

void RhsBrPlus::accept(Visitor *v)
{
  v->visitRhsBrPlus(this);
}

RhsBrPlus *RhsBrPlus::clone() const
{
  return new RhsBrPlus(*this);
}



/********************   RhsBrAst    ********************/
RhsBrAst::RhsBrAst(ListBRHS *p1)
{
  listbrhs_ = p1;

}

RhsBrAst::RhsBrAst(const RhsBrAst & other)
{
  listbrhs_ = other.listbrhs_->clone();

}

RhsBrAst &RhsBrAst::operator=(const RhsBrAst & other)
{
  RhsBrAst tmp(other);
  swap(tmp);
  return *this;
}

void RhsBrAst::swap(RhsBrAst & other)
{
  std::swap(listbrhs_, other.listbrhs_);

}

RhsBrAst::~RhsBrAst()
{
  delete(listbrhs_);

}

void RhsBrAst::accept(Visitor *v)
{
  v->visitRhsBrAst(this);
}

RhsBrAst *RhsBrAst::clone() const
{
  return new RhsBrAst(*this);
}



/********************   RhsBrhsS    ********************/
RhsBrhsS::RhsBrhsS(Ident p1)
{
  ident_ = p1;

}

RhsBrhsS::RhsBrhsS(const RhsBrhsS & other)
{
  ident_ = other.ident_;

}

RhsBrhsS &RhsBrhsS::operator=(const RhsBrhsS & other)
{
  RhsBrhsS tmp(other);
  swap(tmp);
  return *this;
}

void RhsBrhsS::swap(RhsBrhsS & other)
{
  std::swap(ident_, other.ident_);

}

RhsBrhsS::~RhsBrhsS()
{

}

void RhsBrhsS::accept(Visitor *v)
{
  v->visitRhsBrhsS(this);
}

RhsBrhsS *RhsBrhsS::clone() const
{
  return new RhsBrhsS(*this);
}



/********************   RhsBrhsSP    ********************/
RhsBrhsSP::RhsBrhsSP(Ident p1)
{
  ident_ = p1;

}

RhsBrhsSP::RhsBrhsSP(const RhsBrhsSP & other)
{
  ident_ = other.ident_;

}

RhsBrhsSP &RhsBrhsSP::operator=(const RhsBrhsSP & other)
{
  RhsBrhsSP tmp(other);
  swap(tmp);
  return *this;
}

void RhsBrhsSP::swap(RhsBrhsSP & other)
{
  std::swap(ident_, other.ident_);

}

RhsBrhsSP::~RhsBrhsSP()
{

}

void RhsBrhsSP::accept(Visitor *v)
{
  v->visitRhsBrhsSP(this);
}

RhsBrhsSP *RhsBrhsSP::clone() const
{
  return new RhsBrhsSP(*this);
}



/********************   RhsBrhsSA    ********************/
RhsBrhsSA::RhsBrhsSA(Ident p1)
{
  ident_ = p1;

}

RhsBrhsSA::RhsBrhsSA(const RhsBrhsSA & other)
{
  ident_ = other.ident_;

}

RhsBrhsSA &RhsBrhsSA::operator=(const RhsBrhsSA & other)
{
  RhsBrhsSA tmp(other);
  swap(tmp);
  return *this;
}

void RhsBrhsSA::swap(RhsBrhsSA & other)
{
  std::swap(ident_, other.ident_);

}

RhsBrhsSA::~RhsBrhsSA()
{

}

void RhsBrhsSA::accept(Visitor *v)
{
  v->visitRhsBrhsSA(this);
}

RhsBrhsSA *RhsBrhsSA::clone() const
{
  return new RhsBrhsSA(*this);
}



/********************   RhsBrhsTerminal    ********************/
RhsBrhsTerminal::RhsBrhsTerminal(String p1)
{
  string_ = p1;

}

RhsBrhsTerminal::RhsBrhsTerminal(const RhsBrhsTerminal & other)
{
  string_ = other.string_;

}

RhsBrhsTerminal &RhsBrhsTerminal::operator=(const RhsBrhsTerminal & other)
{
  RhsBrhsTerminal tmp(other);
  swap(tmp);
  return *this;
}

void RhsBrhsTerminal::swap(RhsBrhsTerminal & other)
{
  std::swap(string_, other.string_);

}

RhsBrhsTerminal::~RhsBrhsTerminal()
{

}

void RhsBrhsTerminal::accept(Visitor *v)
{
  v->visitRhsBrhsTerminal(this);
}

RhsBrhsTerminal *RhsBrhsTerminal::clone() const
{
  return new RhsBrhsTerminal(*this);
}




/********************   ListRule    ********************/

void ListRule::accept(Visitor *v)
{
  v->visitListRule(this);
}


ListRule *ListRule::clone() const
{
  return new ListRule(*this);
}


/********************   ListRHS    ********************/

void ListRHS::accept(Visitor *v)
{
  v->visitListRHS(this);
}


ListRHS *ListRHS::clone() const
{
  return new ListRHS(*this);
}


/********************   ListBRHS    ********************/

void ListBRHS::accept(Visitor *v)
{
  v->visitListBRHS(this);
}


ListBRHS *ListBRHS::clone() const
{
  return new ListBRHS(*this);
}


/********************   ListDRHS    ********************/

void ListDRHS::accept(Visitor *v)
{
  v->visitListDRHS(this);
}


ListDRHS *ListDRHS::clone() const
{
  return new ListDRHS(*this);
}



}
